apiVersion: v1
kind: Service
metadata:
  name: {{ template "bikeride-biker.fullname" . }}
  labels:
    app: {{ template "bikeride-biker.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.lagomExternalPort }}
      targetPort: {{ .Values.service.lagomInternalPort }}
      protocol: TCP
      name: lagom
    - port: {{ .Values.service.akkaExternalPort }}
      targetPort: {{ .Values.service.akkaInternalPort }}
      protocol: TCP
      name: akka
  selector:
    app: {{ template "bikeride-biker.fullname" . }}
    release: {{ .Release.Name }}
    
