bikeride:
  cassandra:
    service: "db-bikeride-cassandra"
  kafka:
    service: "msg-bikeride-kafka"
  authentication:
    debug: "-d"
    servicedomain: "default.svc.cluster.local"
    secret: "changeme!"
    bindIP: "0.0.0.0"
    #serviceLocatorDNSNameTranslators: "[{ \"biker\" = \"_lagom._tcp.biker-bikeride-biker.default.svc.cluster.local\"}]"
    #serviceLocatorDNSNameTranslators: "{\"^_.+$\"= \"$0\"},{\"biker\"=\"_lagom._tcp.biker-bikeride-biker.default.svc.cluster.local\"},{\"^.*$\"=\"$0\"}"
    #serviceLocatorDNSNameTranslators: "{\"biker\"=\"_lagom._tcp.biker-bikeride-biker.default.svc.cluster.local\"}"
    #serviceLocatorDNSNameTranslators: [{ "^_.+$"   = "$0" },{ "^[^.]+$" = "_lagom._tcp.bikeride-$0.default.svc.cluster.local" },{ "^.*$" = "$0"}]
    #serviceLocatorDNSSRVTranslators: [{"^_lagom[.]_tcp[.](.+)$" = "_lagom._http.$1","^.*$" = "$0"}]    
replicaCount: 1
image:
  repository: bikeride/authentication-lagom-impl
  tag: 0.0.1-SNAPSHOT
  pullPolicy: Always
#  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  lagomExternalPort: 9000
  lagomInternalPort: 9000
  akkaExternalPort: 2551
  akkaInternalPort: 2551
resources: {}
