apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-registry-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  hostPath:
    path: /u01/docker/docker-registry/
