kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-pv-claim
  namespace: kube-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
