apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: kube-public
  labels:
    k8s-app: jenkins
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: jenkins
  ports:
  - name: application
    port: 8080
    protocol: TCP
  - name: node
    port: 50000
    protocol: TCP