apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: bikeride
  labels:
    k8s-app: jenkins
spec:
  type: NodePort
  selector:
    k8s-app: jenkins
  ports:
  - name: application
    port: 8080
    protocol: TCP
    nodePort: 30010
  - name: node
    port: 50000
    protocol: TCP
    nodePort: 30011