apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins-v0
  namespace: kube-public
  labels:
    k8s-app: jenkins
    version: v0
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: jenkins
    version: v0
  template:
    metadata:
      labels:
        k8s-app: jenkins
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          limits:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
        ports:
        - containerPort: 8080
          name: application
          protocol: TCP
        - containerPort: 50000
          name: node
          protocol: TCP
      volumes:
      - name: jenkins-home
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
