apiVersion: "apps/v1beta1"
kind: ReplicationController
metadata:
  name: jenkins
  namespace: bikeride
  labels:
    k8s-app: jenkins
spec:
  replicas: 1
  selector:
    k8s-app: jenkins
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          limits:
            cpu: 100m
            memory: 2048Mi
        ports:
        - containerPort: 8080
          name: application
          protocol: TCP
        - containerPort: 50000
          name: node
          protocol: TCP
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
  volumeClaimTemplates:
  - metadata:
      name: jenkins-data
      annotations:
        volume.beta.kubernetes.io/storage-class: jenkins-fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: jenkins-fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd