apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    k8s-app: jenkins
spec:
  type: NodePort
  selector:
    k8s-app: jenkins
  ports:
  - name: application
    port: 8080
    protocol: TCP
    nodePort: 30010
  - name: node
    port: 50000
    protocol: TCP
    nodePort: 30011
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    k8s-app: jenkins
spec:
  replicas: 1
  selector:
    k8s-app: jenkins
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        resources:
          limits:
            cpu: 100m
            memory: 2048Mi
        ports:
        - containerPort: 8080
          name: application
          protocol: TCP
        - containerPort: 50000
          name: node
          protocol: TCP
