---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        imagePullPolicy: Always
        ports:
        - name: zookeeper
          containerPort: 2181
          protocol: TCP
        - name: kafka
          containerPort: 9092
          protocol: TCP
        env:
          - name: ADVERTISED_HOST
            value: "$HOSTNAME.kafka.default.svc.cluster.local"
          - name: ADVERTISED_PORT
            value: "9092"
#        readinessProbe:
#          httpGet:
#            path: "/_status/circuit-breaker/current"
#            port: 9000
#          initialDelaySeconds: 15
#          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
spec:
  clusterIP: None
  ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-kafka
  name: kafka-kafka
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
      protocol: TCP
  selector:
    app: kafka