apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: application
    port: 8080
    protocol: TCP
    nodePort: 30010
  - name: node
    port: 50000
    protocol: TCP
    nodePort: 30011
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: application
          protocol: TCP
        - containerPort: 50000
          name: node
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
  volumeClaimTemplates:
  - metadata:
      name: jenkins-data
      annotations:
        volume.beta.kubernetes.io/storage-class: jenkins-fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: jenkins-fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd