apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
  - name: application
    port: 8080
    protocol: TCP
  - name: node
    port: 50000
    protocol: TCP
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: jenkins
spec:
  serviceName: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: application
          protocol: TCP
        - containerPort: 50000
          name: node
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 2048Mi
        volumeMounts:
        - name: jenkins-data
          mountPath: /var/jenkins_home
  volumeClaimTemplates:
  - metadata:
      name: jenkins-data
      annotations:
        volume.beta.kubernetes.io/storage-class: jenkins-gluster
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 2Gi
---  
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-gluster
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.111.54.82:8080"
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "Welcome1"
  volumetype: "replicate:2"
allowVolumeExpansion: true  

#https://github.com/kubernetes/examples/tree/master/staging/persistent-volume-provisioning
