---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
      - name: kafka
        image: spotify/kafka
        imagePullPolicy: Always
        ports:
        - name: zookeeper
          containerPort: 2181
          protocol: TCP
        - name: kafka
          containerPort: 9092
          protocol: TCP
        env:
          - name: ADVERTISED_HOST
            #value: "$HOSTNAME.kafka.default.svc.cluster.local"
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: ADVERTISED_PORT
            value: "9092"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-zookeeper
  name: kafka-zookeeper
spec:
  clusterIP: None
  ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
    - name: kafka
      port: 9092
      protocol: TCP
  selector:
    app: kafka
