apiVersion: v1
kind: Service
metadata:
  name: kong-service
spec:
  type: LoadBalancer
  ports:
  - name: kong-proxy
    port: 8000
    targetPort: 8000
    nodePort: 30020
    protocol: TCP
  - name: kong-proxy-ssl
    port: 8443
    targetPort: 8443
    nodePort: 30021
    protocol: TCP
  - name: kong-admin
    port: 8001
    targetPort: 8001
    nodePort: 30022
    protocol: TCP
  - name: kong-admin-ssl
    port: 8444
    targetPort: 8444
    nodePort: 30023
    protocol: TCP
  selector:
    app: kong

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: kong-rc
        app: kong
    spec:
      containers:
      - name: kong
        image: kong
        env:
          - name: KONG_DATABASE
            value: cassandra
          - name: KONG_CASSANDRA_CONTACT_POINTS
            value: cassandra
          - name: KONG_CASSANDRA_KEYSPACE
            value: kong
          - name: KONG_CASSANDRA_REPL_FACTOR
            value: "2"
          - name: KONG_DB_UPDATE_PROPAGATION
            value: "2"
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
        ports:
        - name: admin
          containerPort: 8001
          protocol: TCP
        - name: proxy
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl
          containerPort: 8443
          protocol: TCP
        - name: admin-ssl
          containerPort: 8444
          protocol: TCP
